# Generated by Django 3.2 on 2023-10-27 20:56

import api.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_title_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='genres',
            new_name='genre',
        ),
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.IntegerField(default=0, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(api.validators.get_current_year)], verbose_name='Год выпуска'),
        ),
    ]
